### ISSUE TITLE
RFC: Implementing a query bus for query messages

### ISSUE THREAD

**Issue by matthiasnoback** [SimpleBus/MessageBus#16]
Things to discuss:

- Characteristics of a query bus (e.g. one-to-one relation between queries and query "handlers")
- Return values (e.g. Query::setResult() or probably better: use a Promise-style object)

**Comment by jgoux** [comment]
Hello Matthias.
I think a query bus has a 1-1 relation with its handler.
In opposition to a command, a query bus should return something IMO.

```php
// UserController.php
public function getUser($userId)
{
    $query = new getUser($userId);
    $user = $this->queryBus->execute($query);
    return new JsonResponse($user);
}

public function getPopularUsers()
{
    $query = new getPopularUsers();
    $popularUsers = $this->queryBus->execute($query);
    return new JsonResponse($popularUsers);
}
```

**Comment by josecelano** [comment]
Hi:

1-1 relation
--------------

I am not sure about that. I was talking some days ago with a guy who is doing this:
- REST API end point with a simple service which injects queries in a RabittMQ queue.
- Some workers get queries messages and calculate responses and send the response message (query result) to the queue.
- REST service pulls responses from queue and sends to the http client caller (synchronously).
- More than one worker can be calculating the same response. The service uses the first response from workers.

Return something
----------------------

- What about returning a Message?
- What happens if we do not need the result syncronously?

I have being thinking on a way to implement a Security Service layer in DDD. I think somehow I could use a QueryBus to implement it. As security is a cross-cutting concern I think Message bus could help to keep security layer decentralized.

The basic idea is:
- Use voters (http://symfony.com/doc/current/cookbook/security/voters.html)
- Use a query bus to check authorization.
- There is one authorization query handler for each domain entity.

```php
class BankAccountController
{
	 // ...
	 
	 public function showAction($id, Request $request) 
	 {
		$bankAccountDTO = $this->bankAccountQueryServiceFacade->findById($id);
		$bankAccountId = $bankAccountDTO->getId()
		
		$bankAccountAuthorizationQuery = new BankAccountAuthorizationQuery(
			BankAccountAction::SHOW, 
			$bankAccountId,
			$request->getClientIp()
		)
		$authorization = $this->queryBus->handle($bankAccountAuthorizationQuery);		
	 
		if ($authorization != VoterInterface::ACCESS_GRANTED) {
			throw new AuthorizationFailedException();
		}		
		
		// ... show account info
	 }
{
// Query extends SimpleBus/Message
class BankAccountAuthorizationQuery implements Query
{
	private $action;
	private $accountId;
	private $clientIP;
	
	// getters ...
}
interface VoterInterface {
	public function vote($user, $object, $action);
}
class BankAccountOwnershipVoter implements VoterInterface
{
	public function vote($user, $bankAccount, $action)
	{
		switch($action) {
        	case CashoutAction::CREATE: 
				if ($bankAccount->getOwner()->is($user)) {
					return VoterInterface::ACCESS_GRANTED;
				} else {
					return VoterInterface::ACCESS_DENIED;
				}
			default:
				return VoterInterface::ACCESS_ABSTAIN;
		}
	}
}
class BankAccountIPVoter implements VoterInterface
{
    public function __construct($currentIP, array $blacklistedIp)
    {
        $this->currentIP  = $currentIP;
        $this->blacklistedIp = $blacklistedIp;
    }
	
	public function vote($user, $bankAccount, $action)
	{
		switch($action) {
        	case CashoutAction::CREATE: 
				if (!in_array($this->currentIP, $this->blacklistedIp)) {
					return VoterInterface::ACCESS_GRANTED;
				} else {
					return VoterInterface::ACCESS_DENIED;
				}
			default:
				return VoterInterface::ACCESS_ABSTAIN;
		}
	}
}
class BankAccountAuthorizationQueryHandler implements QuerySubscriber
{
	/**
	* @param Message $query
	* @return mixed
	*/
	public function handle(Message $query)
	{
		$action = $query->getAction();
		$bankAccountId = $query->getBankAccountId();
		$currentIP = $query->getCurrentIP();
		$blacklistedIp = array(); // TODO: Get from constructor
	
		$bankAccountOwnershipVoter = new BankAccountOwnershipVoter();
		$bankAccountIPVoter = new BankAccountIPVoter($currentIP, $blacklistedIp);
		
		$voters = array($bankAccountOwnershipVoter, $bankAccountIPVoter);
		
		// TODO: add services to constructor
		$user = $this->tokenStorageService->getUser();
		$bankAccount = $this->bankAccountRepository->findById(bankAccountId);
		
		foreach($voters as $voter) {
			if ($voter->vote($user, $bankAccount, $action) == VoterInterface::ACCESS_DENIED)
				return VoterInterface::ACCESS_DENIED;
		}
		// Granted access by default
		return VoterInterface::ACCESS_GRANTED;
	}
}
```

Code review: voters could be declared as services and injected into the security layer (in this case the query handler) as Symfony does.

I think this is very similar to:
- Using command handlers instead of services.
- Using controllers with single action: http://php-and-symfony.matthiasnoback.nl/2014/06/framework-independent-controllers-part-3/

**Comment by matthiasnoback** [comment]
Some interesting suggestions there.

The particular example about the voter doesn't completely make sense to me since it can be either solved using a command ("AuthorizeSomething") which throws the UnauthorizedException or using the voter part separately from the query bus (the latter seems to me like the best solution).

Having an asynchronous return value or even multiple combined return values can still be accomplished using promise-style objects (for example using this library: https://github.com/reactphp/promise).

**Comment by josecelano** [comment]
>Having an asynchronous return value or even multiple combined return values can still be >accomplished using promise-style objects (for example using this library: >https://github.com/reactphp/promise).

Cool!! Could you please give a short example?

Regarding my sample I will try to explain my steps to get there.

>using the voter part separately from the query bus

That´s my current solution :-)

I don´t now if this is the rigth place to continue with my sample discussion but at least I want to explain why I thougth about BusQuery for this problem.

This is my first solution (not the last one):

Solution 1
-------------

```php
<?php 
class BankAccountController
{
	 // ...
	 
	 public function showAction($id, Request $request) 
	 {
		$bankAccountDTO = $this->bankAccountQueryServiceFacade->findById($id);
		$bankAccountId = $bankAccountDTO->getId()
		
		try {
			$this->authorizationChecker->checkAuthorization($request, BankAccountAction::SHOW, $bankAccountDTO->getId());
		} catch (AuthorizationFailedException $e) {
			return $this->commonResponsesBuilder->getAuthorizationFailResponse($request);
		}
		
		// ... show account info
	 }
{
interface VoterInterface {
	public function vote($user, $object, $action);
}
class BankAccountOwnershipVoter implements VoterInterface
{
	// ...
}
class BankAccountIPVoter implements VoterInterface
{
	// ...
}
class AuthorizationCheckerService 
{
    /**
     * @param $action
     * @param null $entityId
     * @throws AuthorizationFailedException
     */
    function checkAuthorization($action, $entityId=null)
	{
		// TODO:
		// 1.- Get action class from action name
		// 2.- Get entity class from action
		// 3.- Get entity instance from entity repository
		// 4.- Call Symfony isGranted method (if we are using symfony voters)
		if (false === $this->symfonyAuthorizationChecker->isGranted($action, $entityId)) {
			throw new AuthorizationFailedException();
		}
	}
}
```

Drawbacks:
If you have 50 entities you need to inject 50 repositories in the AuthorizationCheckerService or you can get the entity in the controller (presentation layer :-()) and pass to the AuthorizationCheckerService which is the solution in the official Symfony docs: http://symfony.com/doc/current/cookbook/security/voters_data_permission.html#how-to-use-the-voter-in-a-controller
I do not like that because I am trying not to use domain entities in the controller.

Solution 2
-------------

>using a command ("AuthorizeSomething") 

As you have suggested I could use and AuthorizeBankAccountAction command but I discard it becuase I suppose it is a Query not a Command.

Using this solution I could have one BankAccountAuthorizationChecker command handler for each entity. In fact is the same solution I posted before but using a Command instead of a Query.

I have not found good information about authorization in DDD. I do not like ACL I think voters are more flexible and easier to use. @matthiasnoback I am wainting for someone to write a library to implement voters decoupled from Symfony ;-)

**Comment by matthiasnoback** [comment]
This is an interesting discussion, but I'm closing it for now, to get a better vision on the things that need to be done code-wise.

**Comment by marcospassos** [comment]
Returning promises makes things harder and unreliable. Queries are immediate (synchronous), differently of command that have no return and can be executed asynchronously.

**Comment by matthiasnoback** [comment]
You're right, I wouldn't resort to this as well. I'm still not sure about
the usefulness of an actual bus for queries. For commands it's veru useful,
for events slightly less but still quite important. For queries, I don't
know. What exactly would it mediate? Or maybe I'm missing something....
Op 15 jun. 2015 19:15 schreef "Marcos Passos" <notifications@github.com>:

**Comment by josecelano** [comment]
I have found this library which uses a Query class:
https://github.com/prooph/common/blob/master/src/Messaging/Query.php
and a QueryBus class:
https://github.com/prooph/service-bus/blob/master/src/QueryBus.php
