### ISSUE TITLE
Idea: Event Interface

### ISSUE THREAD

**Issue by farconada** [SimpleBus/MessageBus#2]
Event should have a method occurredOn() cause an event that is something inmutable is always related to a DateTime

**Comment by matthiasnoback** [comment]
Thanks for your suggestion. And I agree on events "occurring on one specific moment in time" and also about them being immutable. How exactly people want to implement the "occurred on" timestamp depends on their situation. Maybe they want to be very precies and use microseconds or something for this. So it will not become a part of the library. Especially since you can very easily introduce your own message types which extend `Event`.

**Comment by farconada** [comment]
"public function ocurredOn();" is not specific to \Date \DateTime etc.
I could agree with the idea of not implementing it, it's not restrictive although convinient

**Comment by matthiasnoback** [comment]
Alright, I think separate libraries with these kinds of more specific/convenient classes would be a great idea. Maybe after I finish this project :)

**Comment by matthiasnoback** [comment]
Closing this for now. I'm open to suggestions for other libraries that have more specialized implementations of events/commands. Thanks @farconada!
