### ISSUE TITLE
command_handler tag handles attribute fails on leading \

### ISSUE THREAD

**Issue by dbu** [SimpleBus/MessageBus#22]
imho we need a `ltrim($handles, '\\')` for the class name. if you can point me to the right direction i am happy to do a pull request.

**Comment by ruudk** [comment]
I think it happens here: https://github.com/SimpleBus/SymfonyBridge/blob/master/src/DependencyInjection/Compiler/CollectServices.php#L28

**Comment by dbu** [comment]
indeed, for the symfony container tag i guess i would need to search in
the compiler passes. but maybe this is something that should be solved
in general, in the place where the map to dispatch the commands / events
is built

**Comment by matthiasnoback** [comment]
So: https://github.com/SimpleBus/MessageBus/blob/master/src/Name/ClassBasedNameResolver.php#L16 returns the "official" FQCN, which is without a leading back-slash. This means that if this is later on matched with a key here: https://github.com/SimpleBus/MessageBus/blob/master/src/Handler/Map/LazyLoadingMessageHandlerMap.php#L31 then these should be exactly the same. A name however can also be returned by the `name()` method of a message, if it implements the `NamedMessage` interface. Hence I don't think we should just start trimming the leading backslash from the name automatically, since the name should really be taken quite literally.

If we would trim it, just because it's easier to work with, then I'd say we'd best to it in the compiler pass. What are your thoughts?

**Comment by dbu** [comment]
ah, i see, its not necessarily always by FQN. is there any other place where we register message handlers by class name? we should cleanup the FQN it in all places where it occurs.

**Comment by matthiasnoback** [comment]
@dbu We can do this in the compiler passes ([here](https://github.com/SimpleBus/SymfonyBridge/blob/master/src/DependencyInjection/Compiler/RegisterHandlers.php#L49) and [here](https://github.com/SimpleBus/SymfonyBridge/blob/master/src/DependencyInjection/Compiler/RegisterSubscribers.php#L49)). I only hope that nobody uses a `\` as the first character for their command names (if anybody doesn't use the class-based names anyway). ;)

**Comment by matthiasnoback** [comment]
Hmm, this has been fixed already :)
