### ISSUE TITLE
Improve "Could not find a callable for name NameOfCommand" exception

### ISSUE THREAD

**Issue by ruudk** [SimpleBus/MessageBus#28]
Maybe it would be better for new users to say "Could not find a handler for Command, maybe you forgot to register it?"

![screen shot 2015-05-20 at 16 27 11](https://cloud.githubusercontent.com/assets/104180/7728045/160f1776-ff0d-11e4-851a-71b3d8c3dc13.png)

**Comment by matthiasnoback** [comment]
The problem is: the exception is thrown at a lower level of abstraction (callables instead of message handlers). We can catch this exception and throw a more specific one in the message handler resolver (https://github.com/SimpleBus/MessageBus/blob/master/src/Handler/Resolver/NameBasedMessageHandlerResolver.php). In fact, that would be a great idea! This would be a BC for `SimpleBus/Asynchronous` though, since it catches the `UndefinedCallable` exception to determine if a message should be sent to the queue.

**Comment by matthiasnoback** [comment]
@ruudk As mentioned, we can only do this at a next major version, so I'll keep it open, but am not going to do this soon... Guess I should have been thinking harder about it when I turned the exact type of the exception into a dependency of other packages ;)

**Comment by sourcerer-mike** [comment]
Hello.

I would love to see this not throwing any exception (or configurable allow commands without handlers).
Sometimes I just want to disable a command even if it goes through the bus.

Thanks for this great package. Keep going! Prooph is still a mess to me while the simplebus is ... simple :D 
Cheers!

**Comment by userdude** [comment]
Man, I hit this all the time... I am good at forgetting this step. :) Thank you @ruudk. 👍
