### ISSUE TITLE
Query messages

### ISSUE THREAD

**Issue by marcospassos** [SimpleBus/MessageBus#31]
Mathias,

Any plans of releasing query message buses?

**Comment by cmodijk** [comment]
Check #16

**Comment by marcospassos** [comment]
So, any plas for releasing?

Em sábado, 13 de junho de 2015, Cliff Odijk <notifications@github.com>
escreveu:

**Comment by matthiasnoback** [comment]
@marcospassos As you may have read in the other thread, the bus has no return value (since strict command/query segregation doesn't allow for one). Changing this would be a BC break, since middlewares would have to pass the return value along, and existing ones don't do that. As I don't to release new major versions again, this is it I'm afraid.

A solution would be, as suggested in the other thread as well, to use the message object itself as a carrier for the response/result as well. Or use "promises" to wait for a result. However, that might not fit very well with a traditional request/response cycle.

**Comment by marcospassos** [comment]
@matthiasnoback I'm currently using tactician.thephpleague.com with good results. Their approach allows handlers return a value (leaving the responsability of doing the right thing to the developer, such as return and expect a value for queries and nothing for commands), as you suggested.

Btw, congratualations for this nice initiative!

**Comment by matthiasnoback** [comment]
Of course, that's a good alternative :) Closing this issue for now.
