### ISSUE TITLE
Add event subscriber on the fly

### ISSUE THREAD

**Issue by ruudk** [SimpleBus/MessageBus#32]
Is there a way to add event subscribers on the fly?

Something like:
```php
$this->get('event_bus')->on(UserCreatedEvent::class, function(UserCreatedEvent $event) {
    // do something
});
```

If you can point me in the right direction, maybe I can add a PR?

**Comment by ruudk** [comment]
Proof of concept:
```php
class CallableMiddleware implements MessageBusMiddleware
{
    /**
     * @var string
     */
    private $event;

    /**
     * @var callable
     */
    private $callable;

    /**
     * @param string $event
     * @param callable $callable
     */
    public function __construct($event, callable $callable)
    {
        $this->event = $event;
        $this->callable = $callable;
    }

    public function handle($command, callable $next)
    {
        if(get_class($command) === $this->event) {
            call_user_func($this->callable, $command);
        }

        $next($command);
    }
}
```

```php
$this->get('event_bus')->appendMiddleware(new CallableMiddleware(UserLoggedInEvent::class, function(UserLoggedInEvent $event) {
    // do something
}));
```

**Comment by matthiasnoback** [comment]
Thanks for bringing this up!
I'm not really sure if an event subscriber should be registered conditionally. Can you describe your use case?

**Comment by ruudk** [comment]
We have a large flow (with multiple steps) to create a draft listing. Every draft is connected to an event. You can choose existing events and create a new event.

We have a `ChangeEventCommand` to set the event on the draft. 

Whenever someone creates a new Event I want to listen to the `EventCreatedEvent` to get the EventId and use that as input for a new command, something like this:

```php
/**
 * Listen to the EventCreatedEvent to automatically run the ChangeEventCommand
 */
$this->onCommandBusEvent(EventCreatedEvent::class, function(EventCreatedEvent $event) use ($draft) {
    $this->handleUserCommand(new ChangeEventCommand(
        $draft,
        $event->getEventId()
    ));
});
$this->handleCommand($command);
```

The main problem is that I use auto incremented ids returned by MySQL. So the only way to get the id of the inserted Event is to listen to the event.

**Comment by ruudk** [comment]
I understand that it's not a good thing to have this kind of things but sometimes it can help a lot. 

Another solution would be to set the `EventId` of the newly created event inside the `CreateEventCommand` but I think that's really ugly.

**Comment by matthiasnoback** [comment]
Hi @ruudk! If you'd like to use auto-incrementing ids, you might still consider generating the id before sending the command. Doctrine even supports this kind of Id generation (though personally I never used it).

I think that we shouldn't add this functionality to the library itself. I only want to support configuration-time event listeners (no runtime listeners) since I consider this a best practice. But, as you just demonstrated, it is very easy to create such a middleware in your own project.

Why do I want configuration-time event listeners, you may ask :) Well, where would you call `appendMiddleware()`? If it's in the controller, you immediately lose one of the biggest advantages of using the command bus - reusabiliy within the same application. If it's outside of that, it might as well be at configuration-time.

**Comment by matthiasnoback** [comment]
@ruudk  Do you have any questions/suggestions? Otherwise, I'd like to close this issue :)

**Comment by ruudk** [comment]
Thanks for your reply. I know that auto-incrementing ids are the problem here. But sometimes you can't change them in an existing application.

I'll use my own middleware for now. Thanks :)

**Comment by matthiasnoback** [comment]
@ruudk Totally understand that :) Good luck! And thanks for all your questions/comments/suggestions, keep them coming!
