### ISSUE TITLE
Exception catching for event subscribers

### ISSUE THREAD

**Issue by pascaldevink** [SimpleBus/MessageBus#38]
Currently, whenever a subscriber to an event throws an exception, the exception is passed through upstream as-is and because of that, execution of the other subscribers is halted.
This was a bit confusing to me, as I expected each subscriber to be executed atomically (even if executed synchronously). 

I also think it's simple to catch thrown exceptions in the middleware, put them in a collection and throw a specialised `SubscriberFailed` exception with the collection of exceptions as parameter. This way, upstream callers can cleanly handle the exceptions, while the other subscribers are not affected.

Would this fit in the current `NotifiesMessageSubscribersMiddleware`? Or could it be a separate middleware handler that one can choose to use instead?

**Comment by matthiasnoback** [comment]
Thanks for reporting this long-standing issue! I knew it exists, but: I wasn't sure how to handle it. This is my reasoning for leaving it as-is: 
1. Other event management tools I know of in PHP just let any exception in a listener bubble up, so I thought it would be more intuitive if MessageBus didn't do this either. 
2. To collect the exceptions by default and throw them all together can't be standard behavior I guess because in one situation it makes sense to continue processing the other events, in others it doesn't. 
3. What you're really looking for (I guess) is a retry mechanism: everything an event listener does is important to your application, so you can't afford to simply ignore a failure. If the exception is caused by some kind of a bug, then it doesn't matter if you only get this one exception (e.g. a `LogicException`). If the exception is caused by some external thing breaking or returning unexpected results (e.g. a `RuntimeException`), then I'd suggest moving the event subscriber logic offline and let it be handled by a message consumer (like the RabbitMQ or Bernard consumers for SimpleBus).

I'm curious about your (and anybody else's) thoughts here.

I also think it would still be interesting to collect and rethrow bundled exceptions, but it can't be the default style of handling exceptions (or it would require a new major version...). The behavior should be configurable via a constructor argument of `NotifiesMessageSubscribersMiddleware` I think. If you'd like to work on it: I'm happy to add it to this package.
By the way, it would then be nice to have a config option in SimpleBus/SymfonyBridge to enable this behavior too.
