### ISSUE TITLE
FinishesHandlingMessageBeforeHandlingNext is OK?

### ISSUE THREAD

**Issue by unkind** [SimpleBus/MessageBus#58]
Hi,

I was thinking about the [FinishesHandlingMessageBeforeHandlingNext](https://github.com/SimpleBus/MessageBus/blob/master/src/Bus/Middleware/FinishesHandlingMessageBeforeHandlingNext.php) middleware.
I might be wrong, so feel free to correct me.

The problem is that this middleware throws exceptions from child command handlers. I don't expect these exceptions when I handle parent command.

In my opinion, it makes sense to do not bubble up exceptions thrown by event listeners. Event might be handled in theory in an indefinite point of time: event handlers behave much like `__destruct` in this case. For example, they might be handled in shutdown function or RabbitMQ queue. One should not rely on these exceptions while handling parent command.

Regarding transactions overlapping, I think there is no such issue since you first should commit transaction and only then handle events.

So it makes me think that `FinishesHandlingMessageBeforeHandlingNext` is a bad practice.

Any thoughts?

**Comment by cmodijk** [comment]
> Regarding transactions overlapping, I think there is no such issue since you first should commit transaction and only then handle events.

This is why it exists we have a middleware which commits the transaction for you if you use doctrine . In this case if you fire a command inside a other command handler you are in the middle of a transaction en doing other work in a second handler might have a impact on each other. With this class we are also forcing you to think about what is happening in a handler to make sure you finish a job first and then handle the rest of the work. 

What i personally suggest is not handle a other command while in a other command. The fact is that while you dispatch the first command and that gets validated and send to the handler you already have acces to the domain layer of you application en you should just do the work.

**Comment by unkind** [comment]
> In this case if you fire a command inside a other command handler

I didn't even imagine this case. 

> With this class we are also forcing you to think about what is happening in a handler to make sure you finish a job first and then handle the rest of the work.

It would force if it threw exception `DoNotCallNestedCommandLikeThat`. 

> you already have acces to the domain layer of you application en you should just do the work

Putting 2 aggregate roots into single command handler (and, hence, into single transaction) is not solution as well.
They can be from different bounded contexts and they can be even on different servers. 
They should be handled separately, usually I use events for it. Event handlers in most cases are synchronous, so `FinishesHandlingMessageBeforeHandlingNext` puts nested command in a queue. And here we have a problem I just described above.

_TL;DR_ My points:
* throw exception, don't queue nested command ("nested" means we start to handle second command while transaction of the first one is not committed yet); 
* always catch exceptions from event handlers, don't let them bubble up.

**Comment by holtkamp** [comment]
A related question about [finish handling a command, before handling the next](http://simplebus.github.io/MessageBus/doc/command_bus.html#finish-handling-a-command-before-handling-the-next)

In an e-commerce system, to realize the Payment of an Order, we got a PayOrderCommand which contains some form data about the Payment and is posted on a CommandBus. The Handler determines the preferred PaymentMethod, initiates API Clients, etc. 

It *is* possible that for a certain PaymentMethod an OAuth2 AccessToken needs to be refreshed, for which a RefreshAccessTokenCommand is available. 

However, this results in a situation with nested Commands where the nested one should be finished before the parent continues / completes:

- PayOrderCommand => "oops, OAuth2 AccessToken is expired! Refresh it:"
  - RefreshAccessTokenCommand => "yup, understood, refreshing, then you can proceed"
 
When using the FinishesHandlingMessageBeforeHandlingNext middleware, this results in problems, since the PayOrderCommand will be completed firstand will fail due to an expired AccessToken. 

What would be the most elegant way to deal with this? Are nested Commands "not done", or can their use be justified in this case?

An approach to stick to purely sequential Command handling seems to:

- PayOrderCommand => fails miserably due to a "AccessTokenExpiredException"
- which is caught and issues a RefreshAccessTokenCommand
- after which a second PayOrderCommand is issued, which now fails

However, now the application component that issues the PayOrderCommand should now be aware of implementation details like AccessTokenExpiredException, etc. Which seems wrong...

**Comment by unkind** [comment]
@holtkamp I have feeling that your problem comes from the fact that you use commands for non-atomic operations: you have some kind of process if you can interrupt it with access token refreshing.

**Comment by holtkamp** [comment]
@unkind indeed, now I am looking to get this 'process' atomic again... 

The current approach is (since we use [DCI](http://stackoverflow.com/questions/378629/dci-data-context-and-interaction-successor-to-mvc)), to have the CommandHandler instantiate and execute a Context (which is like a UseCase) instead of issuing a new Command. 

So the flow I used now is:
- Request gets routed to Controller
- Controller assembles a Command and submits it to CommandBus
- CommandBus determines which CommandHandler should handle the Command
- CommandHandler assembles a Context and executes it

Taken into account that:
- Commands are typically small objects (easily serializable) with primary data types:
   - ```string $organizationUuid```
   - ```string $orderUuid```
- Contexts use actual Domain Entities:
  - ```Organization $organization```
  - ```Order $order```

This works nice, but feedback from others would be nice...
