### ISSUE TITLE
Release next Major version

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/MessageBus#72]
I'm currently in de proces of releasing the next major version of al the packages. 

Package | Current version | New version
-- | -- | --
[simple-bus/asynchronous](https://github.com/SimpleBus/Asynchronous/releases) | 2.1.0 | 3.0.0
[simple-bus/asynchronous-bundle](https://github.com/SimpleBus/AsynchronousBundle/releases) | 2.3.0 | 3.0.0
[simple-bus/doctrine-dbal-bridge](https://github.com/SimpleBus/DoctrineDBALBridge/releases) | 1.0.0 | 2.0.0
[simple-bus/doctrine-orm-bridge](https://github.com/SimpleBus/DoctrineORMBridge/releases) | 4.0.0 | 5.0.0
[simple-bus/jms-serializer-bridge](https://github.com/SimpleBus/JMSSerializerBridge/releases) | 1.0.3 | 2.0.0
[simple-bus/jms-serializer-bundle-bridge](https://github.com/SimpleBus/JMSSerializerBundleBridge/releases) | 2.0.2 | 3.0.0
[simple-bus/message-bus](https://github.com/SimpleBus/MessageBus/releases) | 2.2.2 | 3.0.0
[simple-bus/rabbitmq-bundle-bridge](https://github.com/SimpleBus/RabbitMQBundleBridge/releases) | 3.1.0 | 4.0.0
[simple-bus/serialization](https://github.com/SimpleBus/Serialization/releases) | 2.0.1 | 3.0.0
[simple-bus/bernard-bundle-bridge](https://github.com/SimpleBus/SimpleBusBernardBundleBridge/releases) | 1.1.0 | 2.0.0
[simple-bus/symfony-bridge](https://github.com/SimpleBus/SymfonyBridge/releases) | 4.1.5 | 5.0.0

**Comment by TNAJanssen** [comment]
Great, can I help in someway?

**Comment by cmodijk** [comment]
@TNAJanssen Thanks for asking. I don't know i'm know changing the `composer.json` files but i really want this https://github.com/SimpleBus/DoctrineORMBridge/pull/4 to get merged before I release it today. So i'm going to test this pull and if i don't have any questions i will merge it and release everything.

**Comment by cmodijk** [comment]
Does any one know how i test the new tags locally before releasing them? I tried the "path" "repositories" type but that is not passing the tags.

**Comment by cmodijk** [comment]
Done! The release is done and live, Happy Coding everyone!

**Comment by holtkamp** [comment]
While upgrading some packages, I noticed this BernardBundle is deprecated / read-only

https://github.com/SimpleBus/BernardBundleBridge/releases/2.0.0

I searched a bit but can not find any "Bernard" related stuff in this monorepository, is that correct?

**Comment by ruudk** [comment]
That's correct. We didn't want to support that anymore. But it's still working , but as a separate repo.

**Comment by cmodijk** [comment]
@holtkamp That i correct. @ruudk and I never used it and there is nobody who is maintaining it so we never included it in our switch to the mono repo. The biggest blocking thins for us where these 2 issues.
- https://github.com/SimpleBus/BernardBundleBridge/issues/10
- https://github.com/SimpleBus/BernardBundleBridge/issues/6

**Comment by holtkamp** [comment]
Thanks @ruudk and @cmodijk for the responses. 

Indeed, something like https://github.com/queue-interop/queue-interop also caught my attention and seems like the proper way to go. A quick search indicates that @lakiboy is working in this 😃:

- https://github.com/damax-solutions/enqueue-simple-bus-queue-interop

**FYI regarding the BernardBundle**
I actually only use a very small section of the BernardBundle: 

[```\SimpleBus\BernardBundleBridge\BernardConsumer```](https://github.com/SimpleBus/BernardBundleBridge/blob/cb95e795b9643bcc26bce7f498ec9338dfa2cf66/src/BernardConsumer.php)
[```\SimpleBus\BernardBundleBridge\BernardPublisher```](https://github.com/SimpleBus/BernardBundleBridge/blob/cb95e795b9643bcc26bce7f498ec9338dfa2cf66/src/BernardPublisher.php)

And some custom specializations of these classes to make it easier to have them injected as dependencies:

- ```\SimpleBus\BernardBundleBridge\Consumer\CommandBus```
- ```\SimpleBus\BernardBundleBridge\Consumer\EventBus```
- ```\SimpleBus\BernardBundleBridge\Publisher\CommandBus```
- ```\SimpleBus\BernardBundleBridge\Publisher\EventBus```

So this should be fairly easy to re-factor "someday", thanks guys!

**Comment by lakiboy** [comment]
I'm not working on it per se. It was done and used in one of my projects with enqueue's _Redis_ transport. Should work with any transport actually, but I haven't tried.

The main problem with SimpleBus' for me now is domain events. By original design the domain events are meant to be handled by the same project/app i.e. with domain listener. We had to implement a whole set of SimpleBus customizations in order to serialise these events to _json_, validate it with json schema and send to e.g. _RabbitMQ_. The interested service consumes the event by validating envelope's json schema, extracts the message out of it and validates it too and then dispatches to a handler i.e. application layer, not domain layer (as with domain listener).

Not sure SimpleBus supports modern use-cases any more. However, I still think this is the best lib out there even Today. Nicely done and very extensible. And honestly there is no much choice: Tactitian, Broadway, Prooph, Symfony messenger. The latter I still examining and not really like it.

What I really need is [eventsource](https://github.com/eventsaucephp/eventsauce) with SimpleBus as a transport. Might work on it in the future.
