### ISSUE TITLE
Question: Can 1 Command trigger the handling of another command?

### ISSUE THREAD

**Issue by woutersamaey** [SimpleBus/MessageBus#78]
We've run into an existing Command that while being handled, should run the handling of another Command.

Can command handling be nested this way?

At present, we can't get it to work, because the handle() method on the inner command is never run.
I'm guessing this has to do with the Command handling sequence / lifecyle and the CommandBus was not designed to work this way.

**Comment by cmodijk** [comment]
We have a middleware called [`FinishesHandlingMessageBeforeHandlingNext`](https://github.com/SimpleBus/MessageBus/blob/master/src/Bus/Middleware/FinishesHandlingMessageBeforeHandlingNext.php) which should handle the command after the current command is done. It is by design that the command is never handled at the moment you try to send it inside the other command.  

The reason behind this is that when the command you trigger inside a other command fails both command fails and you don't want that to happen and to revert your transaction.

**Comment by tomhaj** [comment]
@woutersamaey you can also send Event message using event message bus inside command. Using event handler you can trigger new command.
